import express from 'express';
import grokResearchService from '../services/grokResearchService';

const router = express.Router();

// Generate discussion guide using PRD and Research Plan
router.post('/', async (req, res) => {
  try {
    const { researchPlan, prdData, userPrompt } = req.body;

    if (!researchPlan) {
      return res.status(400).json({ error: 'Research plan is required' });
    }

    console.log('📋 Generating AI discussion guide with Grok...');
    console.log('Research Plan available:', !!researchPlan);
    console.log('PRD Data available:', !!prdData);
    console.log('🔑 Grok API Key available:', process.env.GROK_API_KEY ? 'YES' : 'NO');

    // Use Grok Research Service for AI-powered discussion guide generation
    const result = await grokResearchService.generateDiscussionGuide({
      project: {
        name: prdData?.name || researchPlan?.projectName || 'Product Research',
        description: prdData?.description || researchPlan?.description || 'Product concept'
      },
      researchPlan: researchPlan,
      prdData: prdData
    });

    console.log('✅ Discussion Guide Generation completed');
    console.log('Generated by:', result.metadata.generatedBy);
    console.log('Confidence:', result.metadata.confidence);
    console.log('Source:', result.metadata.source);
    console.log('Content length:', result.content?.length || 0);

    // Parse the AI response into structured discussion guide
    const discussionGuide = parseDiscussionGuideResponse(result.content, researchPlan);
    
    res.json({
      success: true,
      discussionGuide: discussionGuide,
      metadata: result.metadata
    });

  } catch (error) {
    console.error('❌ Error generating discussion guide:', error);
    res.status(500).json({ 
      error: 'Failed to generate discussion guide',
      details: error instanceof Error ? error.message : 'Unknown error'
    });
  }
});

// Helper function to parse AI response into structured discussion guide
function parseDiscussionGuideResponse(content: string, researchPlan: any) {
  try {
    // Try to parse as JSON first
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      try {
        return JSON.parse(jsonMatch[0]);
      } catch (e) {
        // If JSON parsing fails, continue with markdown parsing
      }
    }

    // Parse markdown content into structured format
    const lines = content.split('\n');
    const discussionGuide: any = {
      title: 'Discussion Guide',
      projectName: researchPlan?.projectName || 'Product Research',
      objectives: [],
      methodology: 'Semi-structured interviews',
      introduction: '',
      moderatorNotes: [],
      sessionFlow: [],
      questions: [],
      activities: []
    };

    let currentSection = '';
    let questionId = 1;
    let activityId = 1;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      
      if (line.startsWith('# ')) {
        discussionGuide.title = line.replace('# ', '');
      } else if (line.startsWith('## ')) {
        currentSection = line.replace('## ', '');
      } else if (line.startsWith('### ')) {
        currentSection = line.replace('### ', '');
      } else if (line.startsWith('**') && line.includes('**')) {
        // Bold text - likely a question or important note
        if (currentSection.toLowerCase().includes('question') || 
            currentSection.toLowerCase().includes('interview')) {
          discussionGuide.questions.push({
            id: questionId.toString(),
            section: currentSection,
            question: line.replace(/\*\*/g, ''),
            followUp: '',
            category: 'General',
            objectives: ['Gather user insights']
          });
          questionId++;
        }
      } else if (line.startsWith('- ') || line.startsWith('* ')) {
        const content = line.replace(/^[-*] /, '');
        
        if (currentSection.toLowerCase().includes('note') || 
            currentSection.toLowerCase().includes('moderator')) {
          discussionGuide.moderatorNotes.push(content);
        } else if (currentSection.toLowerCase().includes('flow') || 
                   currentSection.toLowerCase().includes('session')) {
          discussionGuide.sessionFlow.push(content);
        } else if (currentSection.toLowerCase().includes('objective')) {
          discussionGuide.objectives.push(content);
        } else if (currentSection.toLowerCase().includes('activity')) {
          discussionGuide.activities.push({
            id: activityId.toString(),
            name: content,
            description: content,
            duration: '15 minutes',
            materials: []
          });
          activityId++;
        }
      } else if (line.length > 0 && !line.startsWith('#')) {
        // Regular content
        if (currentSection.toLowerCase().includes('introduction')) {
          discussionGuide.introduction += line + ' ';
        }
      }
    }

    // Clean up introduction
    discussionGuide.introduction = discussionGuide.introduction.trim();

    // If no questions were found, add some default ones
    if (discussionGuide.questions.length === 0) {
      discussionGuide.questions = [
        {
          id: '1',
          section: 'Introduction',
          question: 'Can you tell me a little about yourself and your background?',
          followUp: 'What do you do for work? What are your main interests?',
          category: 'Demographics',
          objectives: ['Build rapport', 'Understand context']
        },
        {
          id: '2',
          section: 'Current Experience',
          question: 'How do you currently handle [relevant task]?',
          followUp: 'What tools or methods do you use? What works well? What\'s frustrating?',
          category: 'Current State',
          objectives: ['Understand current behavior', 'Identify pain points']
        },
        {
          id: '3',
          section: 'Needs & Goals',
          question: 'What would make this process easier or better for you?',
          followUp: 'What features or improvements would be most valuable?',
          category: 'Needs Assessment',
          objectives: ['Identify user needs', 'Prioritize features']
        }
      ];
    }

    return discussionGuide;

  } catch (error) {
    console.error('Error parsing discussion guide response:', error);
    
    // Return a basic fallback structure
    return {
      title: 'Discussion Guide',
      projectName: researchPlan?.projectName || 'Product Research',
      objectives: ['Understand user needs and behaviors'],
      methodology: 'Semi-structured interviews',
      introduction: 'This discussion guide is designed to gather insights about user needs, behaviors, and preferences.',
      moderatorNotes: [
        'Build rapport with participants',
        'Ask open-ended questions',
        'Probe for deeper insights',
        'Take detailed notes'
      ],
      sessionFlow: [
        'Introduction and warm-up (5-10 minutes)',
        'Background and current experience (15-20 minutes)',
        'Needs and goals exploration (15-20 minutes)',
        'Product concept evaluation (20-25 minutes)',
        'Wrap-up and next steps (5-10 minutes)'
      ],
      questions: [
        {
          id: '1',
          section: 'Introduction',
          question: 'Can you tell me a little about yourself?',
          followUp: 'What do you do for work? What are your main interests?',
          category: 'Demographics',
          objectives: ['Build rapport', 'Understand context']
        },
        {
          id: '2',
          section: 'Current Experience',
          question: 'How do you currently handle [relevant task]?',
          followUp: 'What works well? What\'s frustrating?',
          category: 'Current State',
          objectives: ['Understand current behavior', 'Identify pain points']
        },
        {
          id: '3',
          section: 'Needs & Goals',
          question: 'What would make this process better for you?',
          followUp: 'What features would be most valuable?',
          category: 'Needs Assessment',
          objectives: ['Identify user needs', 'Prioritize features']
        }
      ],
      activities: [
        {
          id: '1',
          name: 'Current Process Mapping',
          description: 'Have participants walk through their current process step-by-step',
          duration: '10 minutes',
          materials: ['Whiteboard', 'Sticky notes']
        },
        {
          id: '2',
          name: 'Feature Prioritization',
          description: 'Ask participants to rank potential features by importance',
          duration: '15 minutes',
          materials: ['Feature cards', 'Ranking sheet']
        }
      ]
    };
  }
}

export default router;