import express from 'express';
import OpenAI from 'openai';
import axios from 'axios';
import simplePRDService from '../services/simplePRDService';
import grokPRDService from '../services/grokPRDService';
import advancedPRDService from '../services/advancedPRDService';
import claudePRDService from '../services/claudePRDService';

const router = express.Router();

// Initialize OpenAI client (fallback)
const openai = process.env.OPENAI_API_KEY && process.env.OPENAI_API_KEY !== 'dummy-key' 
  ? new OpenAI({
      apiKey: process.env.OPENAI_API_KEY
    })
  : null;

// POST /api/prd-generation/generate - Generate PRD using Claude 3.5 Sonnet (Primary)
router.post('/generate', async (req, res) => {
  // Set timeout for the request
  const timeout = setTimeout(() => {
    if (!res.headersSent) {
      res.status(408).json({
        success: false,
        error: 'Request timeout - PRD generation took too long',
        content: 'The PRD generation request timed out. Please try again with a simpler prompt.',
        metadata: {
          generatedAt: new Date().toISOString(),
          generatedBy: 'Timeout Handler',
          confidence: 0,
          source: 'timeout'
        }
      });
    }
  }, 120000); // 2 minute timeout

  try {
    const { prompt, projectData, pmFormData } = req.body;

    console.log('🚀 Generating PRD with Claude 3.5 Sonnet...');
    console.log('Project:', projectData?.name);
    console.log('PM Data available:', !!pmFormData);
    console.log('🔑 Claude API Key available:', process.env.CLAUDE_API_KEY ? 'YES' : 'NO');

    // Check if streaming is requested
    const isStreaming = req.headers.accept?.includes('text/stream') || req.query.stream === 'true';

    if (isStreaming) {
      // Set up streaming response
      res.setHeader('Content-Type', 'text/stream');
      res.setHeader('Cache-Control', 'no-cache');
      res.setHeader('Connection', 'keep-alive');
      res.setHeader('Access-Control-Allow-Origin', '*');
      res.setHeader('Access-Control-Allow-Headers', 'Cache-Control');

      // Generate PRD with streaming
      await generateStreamingPRD(req, res, timeout);
      return;
    }

    // Use Grok PRD Service for AI-powered PRD generation (Primary)
    const result = await grokPRDService.generatePRD({
      prompt,
      projectData,
      pmFormData
    });

    console.log('✅ PRD Generation completed');
    console.log('Generated by:', result.metadata.generatedBy);
    console.log('Confidence:', result.metadata.confidence);
    console.log('Source:', result.metadata.source);
    console.log('Content length:', result.content?.length || 0);

    // Ensure we always return a valid JSON response
    if (!result || typeof result !== 'object') {
      console.error('❌ Invalid result object:', result);
      return res.status(500).json({
        success: false,
        error: 'Invalid response from PRD service',
        content: 'Failed to generate PRD. Please try again.',
        metadata: {
          generatedAt: new Date().toISOString(),
          generatedBy: 'Error Handler',
          confidence: 0,
          source: 'error'
        }
      });
    }

    clearTimeout(timeout);
    res.json(result);

  } catch (error) {
    clearTimeout(timeout);
    console.error('❌ Error generating PRD:', error);
    
    // Fallback to Grok if Claude fails
    try {
      console.log('🔄 Falling back to Grok AI...');
      const grokResult = await grokPRDService.generatePRD({
        prompt: req.body.prompt,
        projectData: req.body.projectData,
        pmFormData: req.body.pmFormData
      });
      
      if (grokResult.success) {
        clearTimeout(timeout);
        return res.json(grokResult);
      }
    } catch (grokError) {
      console.error('❌ Grok fallback also failed:', grokError);
    }
    
    // Fallback to OpenAI if both Claude and Grok fail
    if (openai) {
      try {
        console.log('🔄 Falling back to OpenAI...');
        
        const enhancedPrompt = `You are an expert Product Manager and technical writer. Generate a comprehensive Product Requirements Document (PRD) based on the following information:

${req.body.prompt}

Please generate a professional PRD following Carlin Yuen's framework with:
1. Clear problem statement and opportunity
2. Target users and use cases
3. Current state and competitive landscape
4. Proposed solution with elevator pitch
5. Goals and measurable outcomes
6. Prioritized functional requirements
7. Success metrics and KPIs
8. Technical requirements and constraints
9. Risk assessment
10. Implementation timeline

Format the response as a well-structured markdown document with clear headings and actionable insights.`;

        const completion = await openai.chat.completions.create({
          model: "gpt-4",
          messages: [
            {
              role: "system",
              content: "You are an expert Product Manager and technical writer specializing in creating comprehensive Product Requirements Documents. You follow Carlin Yuen's PRD framework and create clear, actionable, and stakeholder-ready documents."
            },
            {
              role: "user",
              content: enhancedPrompt
            }
          ],
          max_tokens: 4000,
          temperature: 0.7,
        });

        const generatedContent = completion.choices[0]?.message?.content || '';

        clearTimeout(timeout);
        return res.json({
          success: true,
          content: generatedContent,
          metadata: {
            generatedAt: new Date().toISOString(),
            generatedBy: 'OpenAI GPT-4 (Fallback)',
            confidence: 0.9,
            source: 'openai-fallback',
            model: 'gpt-4',
            tokens: completion.usage?.total_tokens || 0
          }
        });

      } catch (openaiError) {
        console.error('❌ OpenAI fallback also failed:', openaiError);
      }
    }
    
    // Final fallback to basic generation
    clearTimeout(timeout);
    res.json({
      success: false,
      error: error instanceof Error ? error.message : 'Failed to generate PRD',
      content: generateFallbackPRD(req.body.projectData, req.body.pmFormData),
      metadata: {
        generatedAt: new Date().toISOString(),
        generatedBy: 'Basic Fallback Generator',
        confidence: 0.5,
        source: 'fallback-error'
      }
    });
  }
});

// Fallback PRD generation function
function generateFallbackPRD(projectData: any, pmFormData: any) {
  const projectName = pmFormData?.projectName || projectData?.name || 'Project';
  const projectDescription = pmFormData?.projectDescription || projectData?.description || 'Product';

  return `# Product Requirements Document: ${projectName}

## 1. Executive Summary

This PRD outlines the development of ${projectName}, a ${projectDescription.toLowerCase()}. The product aims to address key user needs while achieving business objectives through a user-centered design approach.

${pmFormData?.elevatorPitch ? `\n**Elevator Pitch:** ${pmFormData.elevatorPitch}` : ''}

## 2. Problem Statement & Business Context

${pmFormData?.problemStatement ? 
  `**Problem Statement:** ${pmFormData.problemStatement}\n\n**Opportunity:** ${pmFormData.opportunityDescription}` :
  `The current market lacks a comprehensive solution for ${projectDescription.toLowerCase()}. Users face challenges in [specific pain points]. This product addresses these gaps by providing [key value propositions].`
}

## 3. Target Users & Use Cases

${pmFormData?.targetUsers ? 
  `**Target Users:** ${pmFormData.targetUsers}\n\n**Primary Use Cases:** ${pmFormData.primaryUseCases}` :
  `Primary users include target users. Each persona has distinct needs and behaviors that inform our design decisions and feature prioritization.`
}

## 4. Current State & Landscape

${pmFormData?.currentJourney ? 
  `**Current User Journey:** ${pmFormData.currentJourney}\n\n**Competitive Landscape:** ${pmFormData.competitiveLandscape}` :
  `Current state analysis and competitive landscape assessment will be conducted to understand market positioning and opportunities.`
}

## 5. Proposed Solution

${pmFormData?.elevatorPitch ? 
  `**Elevator Pitch:** ${pmFormData.elevatorPitch}\n\n**MVP Value Propositions:**\n${pmFormData.mvpValueProps?.filter((prop: string) => prop.trim()).map((prop: string, index: number) => `${index + 1}. ${prop}`).join('\n')}\n\n**Conceptual Model:** ${pmFormData.conceptualModel || 'To be defined'}` :
  `The proposed solution addresses the identified problems through [key features and capabilities]. This approach provides [value propositions] to target users.`
}

## 6. Goals & Measurable Outcomes

${pmFormData?.goals ? 
  `**Goals:**\n${pmFormData.goals.filter((goal: string) => goal.trim()).map((goal: string, index: number) => `${index + 1}. ${goal}`).join('\n')}\n\n**Success Metrics:**\n${pmFormData.successMetrics.filter((metric: string) => metric.trim()).map((metric: string, index: number) => `${index + 1}. ${metric}`).join('\n')}` :
  `Success will be measured through key performance indicators that align with business objectives and user satisfaction goals.`
}

## 7. Functional Requirements

${pmFormData?.requirements && pmFormData.requirements.length > 0 ? 
  `**Functional Requirements:**\n${pmFormData.requirements.map((req: any) => `[${req.priority}] ${req.description} (Use Case: ${req.useCase}, Category: ${req.category})`).join('\n')}` :
  `Core functionality includes essential features that ensure the product meets user needs and business objectives.`
}

## 8. Technical Requirements & Constraints

Technical specifications and constraints will be defined based on scalability, performance, and integration requirements.

## 9. Risk Assessment

Potential risks and mitigation strategies will be identified and documented to ensure successful project delivery.

## 10. Implementation Timeline

A detailed implementation timeline will be created based on feature prioritization and resource availability.

---

*Generated on ${new Date().toLocaleDateString()} using ProcessCraft AI*
*Based on ${pmFormData ? 'PM input data and ' : ''}Carlin Yuen's PRD framework*`;
}

// POST /api/prd-generation/generate-detailed - Generate detailed PRD with comprehensive structure
router.post('/generate-detailed', async (req, res) => {
  try {
    const { project, template = 'comprehensive' } = req.body;

    console.log('🚀 Generating detailed PRD...');
    console.log('Project:', project?.name);
    console.log('Template:', template);
    console.log('🔑 Claude API Key available:', process.env.CLAUDE_API_KEY ? 'YES' : 'NO');

    // Build comprehensive PRD prompt
    const prompt = buildDetailedPRDPrompt(project, template);
    
    // Call Claude API
    const response = await callClaudeAPI(prompt);
    
    if (response.success) {
      res.json({
        success: true,
        content: response.content,
        metadata: response.metadata
      });
    } else {
      // Fallback to template-based generation
      const fallbackPRD = generateDetailedFallbackPRD(project);
      res.json({
        success: true,
        content: fallbackPRD,
        metadata: {
          generatedAt: new Date().toISOString(),
          generatedBy: 'Detailed Fallback Generator',
          confidence: 0.8,
          source: 'fallback-detailed'
        }
      });
    }

  } catch (error) {
    console.error('❌ Error generating detailed PRD:', error);
    res.json({
      success: false,
      error: error instanceof Error ? error.message : 'Failed to generate detailed PRD',
      content: generateDetailedFallbackPRD(req.body.project)
    });
  }
});

async function callClaudeAPI(prompt: string) {
  try {
    if (!process.env.CLAUDE_API_KEY || process.env.CLAUDE_API_KEY === 'dummy-key') {
      throw new Error('Claude API key not configured');
    }

    const response = await axios.post('https://api.anthropic.com/v1/messages', {
      model: 'claude-3-5-sonnet-20241022',
      max_tokens: 8000,
      temperature: 0.3,
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ]
    }, {
      headers: {
        'x-api-key': process.env.CLAUDE_API_KEY,
        'Content-Type': 'application/json',
        'anthropic-version': '2023-06-01'
      },
      timeout: 120000
    });

    const content = response.data.content[0]?.text || '';
    const inputTokens = response.data.usage?.input_tokens || 0;
    const outputTokens = response.data.usage?.output_tokens || 0;

    return {
      success: true,
      content: content,
      metadata: {
        generatedAt: new Date().toISOString(),
        generatedBy: 'Claude 3.5 Sonnet',
        confidence: 0.95,
        source: 'claude-api',
        model: 'claude-3-5-sonnet-20241022',
        tokens: inputTokens + outputTokens
      }
    };

  } catch (error: any) {
    console.error('Error calling Claude API:', error.response?.data || error.message);
    throw error;
  }
}

function buildDetailedPRDPrompt(project: any, template: string): string {
  return `You are an expert Product Manager. Create a comprehensive, detailed Product Requirements Document (PRD) based on the following information:

PROJECT DETAILS:
- Project Name: ${project.name}
- Description: ${project.description || 'No description provided'}
- Objectives: ${project.prd?.objectives?.join(', ') || 'To be defined'}
- Target Users: ${project.prd?.targetUsers?.join(', ') || 'To be defined'}

Please generate a detailed PRD following this exact structure and format. Use HTML formatting with proper headings, lists, and styling. Make it comprehensive and professional like a real PRD document:

<h1>Product Requirements Document: ${project.name}</h1>

<p><em>If you are new to the project, this document will help you understand the ${project.name}. This document outlines the features, functionality, and user experience requirements. It also provides a high-level overview of the technical considerations and dependencies.</em></p>

<h2>1. Goals</h2>
<h3>1.1 Business Goals</h3>
<ul>
  <li>Increase user engagement by providing an inviting and intuitive experience</li>
  <li>Drive user acquisition and retention through compelling features</li>
  <li>Establish market leadership in the target segment</li>
  <li>Generate sustainable revenue through user value</li>
</ul>

<h3>1.2 User Goals</h3>
<ul>
  <li>Easily understand and navigate the product</li>
  <li>Accomplish primary tasks efficiently</li>
  <li>Have a seamless and enjoyable experience</li>
  <li>Access features and content intuitively</li>
</ul>

<h2>2. User Stories</h2>
<ul>
  <li><strong>As a new user,</strong> I want to quickly understand the product value so that I can decide to continue using it.</li>
  <li><strong>As a returning user,</strong> I want to easily access my previous work so that I can continue where I left off.</li>
  <li><strong>As a power user,</strong> I want advanced features and customization options so that I can optimize my workflow.</li>
  <li><strong>As a mobile user,</strong> I want a responsive experience so that I can use the product on any device.</li>
  <li><strong>As a user,</strong> I want clear navigation so that I can find features quickly.</li>
  <li><strong>As a user,</strong> I want to save my work so that I don't lose my progress.</li>
  <li><strong>As a user,</strong> I want to share my work so that I can collaborate with others.</li>
  <li><strong>As a user,</strong> I want help and support so that I can resolve issues quickly.</li>
</ul>

<h2>3. Functional Requirements</h2>
<h3>3.1 Core Features</h3>
<ul>
  <li><strong>User Authentication & Management:</strong>
    <ul>
      <li>The system shall provide user registration and login functionality</li>
      <li>Users shall be able to reset passwords securely</li>
      <li>User profiles shall be manageable and customizable</li>
      <li>Role-based access control shall be implemented</li>
    </ul>
  </li>
  <li><strong>Content Management:</strong>
    <ul>
      <li>Users shall be able to create, read, update, and delete content</li>
      <li>File upload and storage capabilities shall be provided</li>
      <li>Content categorization and tagging shall be supported</li>
      <li>Search and filtering functionality shall be available</li>
    </ul>
  </li>
  <li><strong>Navigation & Interface:</strong>
    <ul>
      <li>A main navigation menu shall be present and accessible</li>
      <li>Breadcrumb navigation shall be provided for deep pages</li>
      <li>Search functionality shall be prominently available</li>
      <li>User settings and preferences shall be easily accessible</li>
    </ul>
  </li>
</ul>

<h3>3.2 Advanced Features</h3>
<ul>
  <li>Real-time collaboration and sharing capabilities</li>
  <li>Advanced analytics and reporting dashboard</li>
  <li>API integration with third-party services</li>
  <li>Customization and personalization options</li>
  <li>Notification and communication system</li>
</ul>

<h2>4. User Experience (UX) Requirements</h2>
<h3>4.1 Visual Design</h3>
<ul>
  <li>The interface shall use a modern, clean design language</li>
  <li>Color scheme shall be consistent and accessible</li>
  <li>Typography shall be readable and professional</li>
  <li>Icons and imagery shall be clear and meaningful</li>
</ul>

<h3>4.2 Navigation</h3>
<ul>
  <li>Navigation between sections shall be intuitive and smooth</li>
  <li>Transitions between pages shall be fluid and visually pleasing</li>
  <li>Back button functionality shall work consistently</li>
  <li>Deep linking shall be supported for direct access</li>
</ul>

<h3>4.3 Feedback</h3>
<ul>
  <li>All interactive elements shall provide immediate visual feedback</li>
  <li>Loading states shall be clearly indicated</li>
  <li>Error messages shall be clear and actionable</li>
  <li>Success confirmations shall be provided for user actions</li>
</ul>

<h3>4.4 Accessibility</h3>
<ul>
  <li>Text elements shall have sufficient contrast against backgrounds</li>
  <li>Interactive elements shall be large enough for easy interaction</li>
  <li>Keyboard navigation shall be fully supported</li>
  <li>Screen reader compatibility shall be ensured</li>
</ul>

<h2>5. Non-Functional Requirements</h2>
<h3>5.1 Performance</h3>
<ul>
  <li>Page load times shall be under 3 seconds on standard connections</li>
  <li>Interactive elements shall respond within 100ms</li>
  <li>The system shall support 1000+ concurrent users</li>
  <li>Database queries shall be optimized for sub-second response times</li>
</ul>

<h3>5.2 Security</h3>
<ul>
  <li>All data transmission shall be encrypted using HTTPS</li>
  <li>User authentication shall be secure and multi-factor capable</li>
  <li>Regular security audits and vulnerability assessments shall be conducted</li>
  <li>Data privacy and GDPR compliance shall be maintained</li>
</ul>

<h3>5.3 Scalability</h3>
<ul>
  <li>The system shall handle 10x user growth without performance degradation</li>
  <li>Database and infrastructure shall be horizontally scalable</li>
  <li>CDN shall be used for static asset delivery</li>
  <li>Load balancing shall be implemented for high availability</li>
</ul>

<h3>5.4 Maintainability</h3>
<ul>
  <li>Code shall be well-documented and modular</li>
  <li>Automated testing shall cover critical functionality</li>
  <li>Deployment processes shall be automated and reliable</li>
  <li>Monitoring and logging shall be comprehensive</li>
</ul>

<h3>5.5 Compatibility</h3>
<ul>
  <li>The product shall work on modern web browsers (Chrome, Firefox, Safari, Edge)</li>
  <li>Mobile responsiveness shall be ensured across device sizes</li>
  <li>Cross-platform compatibility shall be maintained</li>
  <li>Progressive Web App (PWA) capabilities shall be considered</li>
</ul>

<h2>6. Technical Considerations</h2>
<h3>6.1 Platform & Architecture</h3>
<ul>
  <li><strong>Frontend:</strong> React with TypeScript for type safety</li>
  <li><strong>Backend:</strong> Node.js with Express framework</li>
  <li><strong>Database:</strong> PostgreSQL for relational data, Redis for caching</li>
  <li><strong>Hosting:</strong> Cloud platform (AWS/Azure) with auto-scaling</li>
</ul>

<h3>6.2 Dependencies</h3>
<ul>
  <li>UI component library for consistent design</li>
  <li>State management solution (Redux/Zustand)</li>
  <li>Authentication service (Auth0/Firebase)</li>
  <li>Analytics and monitoring tools</li>
  <li>Third-party API integrations as needed</li>
</ul>

<h3>6.3 Data Management</h3>
<ul>
  <li>User data shall be stored securely and encrypted</li>
  <li>Data backup and recovery procedures shall be in place</li>
  <li>Data retention policies shall be clearly defined</li>
  <li>API rate limiting shall be implemented</li>
</ul>

<h2>7. Future Enhancements (Out of Scope for V1)</h2>
<ul>
  <li>Advanced AI-powered features and recommendations</li>
  <li>Mobile native applications</li>
  <li>Advanced analytics and business intelligence</li>
  <li>Enterprise features and integrations</li>
  <li>Multi-language support and internationalization</li>
  <li>Advanced customization and white-labeling options</li>
</ul>

<h2>8. Success Criteria</h2>
<h3>8.1 Key Performance Indicators (KPIs)</h3>
<ul>
  <li><strong>User Metrics:</strong> Daily Active Users (DAU), Monthly Active Users (MAU), user retention rates</li>
  <li><strong>Engagement Metrics:</strong> Session duration, pages per session, feature adoption rates</li>
  <li><strong>Business Metrics:</strong> Revenue per user, conversion rates, customer lifetime value</li>
  <li><strong>Technical Metrics:</strong> System uptime, response times, error rates</li>
</ul>

<h3>8.2 Success Timeline</h3>
<ul>
  <li><strong>Month 1-3:</strong> Core development and internal testing</li>
  <li><strong>Month 4-6:</strong> Beta launch with limited user group</li>
  <li><strong>Month 7-9:</strong> Public launch and user acquisition</li>
  <li><strong>Month 10-12:</strong> Feature optimization and scaling</li>
</ul>

<hr style="margin: 2rem 0; border: none; border-top: 1px solid #e5e7eb;" />

<p style="color: #6b7280; font-size: 0.875rem; text-align: center;">
  <em>This PRD was generated using ProcessCraft AI and can be edited using the built-in editor.</em><br />
  <em>Last updated: ${new Date().toLocaleDateString()}</em>
</p>

Make the PRD detailed, professional, and actionable. Use specific, measurable requirements where possible. Ensure the content is relevant to the project and provides clear guidance for development teams.`;
}

function generateDetailedFallbackPRD(project: any): string {
  return `
    <h1>Product Requirements Document: ${project.name}</h1>
    
    <p><em>If you are new to the project, this document will help you understand the ${project.name}. This document outlines the features, functionality, and user experience requirements. It also provides a high-level overview of the technical considerations and dependencies.</em></p>
    
    <h2>1. Goals</h2>
    <h3>1.1 Business Goals</h3>
    <ul>
      <li>Increase user engagement by providing an inviting and intuitive experience</li>
      <li>Drive user acquisition and retention through compelling features</li>
      <li>Establish market leadership in the target segment</li>
      <li>Generate sustainable revenue through user value</li>
    </ul>
    
    <h3>1.2 User Goals</h3>
    <ul>
      <li>Easily understand and navigate the product</li>
      <li>Accomplish primary tasks efficiently</li>
      <li>Have a seamless and enjoyable experience</li>
      <li>Access features and content intuitively</li>
    </ul>
    
    <h2>2. User Stories</h2>
    <ul>
      <li><strong>As a new user,</strong> I want to quickly understand the product value so that I can decide to continue using it.</li>
      <li><strong>As a returning user,</strong> I want to easily access my previous work so that I can continue where I left off.</li>
      <li><strong>As a power user,</strong> I want advanced features and customization options so that I can optimize my workflow.</li>
      <li><strong>As a mobile user,</strong> I want a responsive experience so that I can use the product on any device.</li>
    </ul>
    
    <h2>3. Functional Requirements</h2>
    <h3>3.1 Core Features</h3>
    <ul>
      <li>User authentication and profile management</li>
      <li>Content creation and management capabilities</li>
      <li>Search and filtering functionality</li>
      <li>Data visualization and reporting</li>
    </ul>
    
    <h2>4. User Experience (UX) Requirements</h2>
    <h3>4.1 Visual Design</h3>
    <ul>
      <li>Modern, clean interface design</li>
      <li>Consistent color scheme and typography</li>
      <li>Responsive design for all devices</li>
      <li>Accessible design following WCAG guidelines</li>
    </ul>
    
    <h2>5. Non-Functional Requirements</h2>
    <h3>5.1 Performance</h3>
    <ul>
      <li>Page load times under 3 seconds</li>
      <li>Support for 1000+ concurrent users</li>
      <li>99.9% uptime SLA</li>
    </ul>
    
    <h2>6. Technical Considerations</h2>
    <h3>6.1 Technology Stack</h3>
    <ul>
      <li>Frontend: React with TypeScript</li>
      <li>Backend: Node.js with Express</li>
      <li>Database: PostgreSQL with Redis caching</li>
      <li>Hosting: Cloud platform with auto-scaling</li>
    </ul>
    
    <hr style="margin: 2rem 0; border: none; border-top: 1px solid #e5e7eb;" />
    
    <p style="color: #6b7280; font-size: 0.875rem; text-align: center;">
      <em>This PRD was generated using ProcessCraft AI and can be edited using the built-in editor.</em><br />
      <em>Last updated: ${new Date().toLocaleDateString()}</em>
    </p>
  `;
}

// Streaming PRD generation function
async function generateStreamingPRD(req: any, res: any, timeout: NodeJS.Timeout) {
  try {
    const { prompt, projectData, pmFormData } = req.body;

    // Send initial response
    res.write(`data: ${JSON.stringify({
      type: 'start',
      message: 'Starting PRD generation...'
    })}\n\n`);

    // Generate PRD using the Grok service
    const result = await grokPRDService.generatePRD({
      prompt,
      projectData,
      pmFormData
    });

    if (!result || !result.content) {
      throw new Error('No content generated');
    }

    // Simulate streaming by sending content in chunks
    const content = result.content;
    const chunkSize = 100; // Characters per chunk
    let index = 0;

    const sendChunk = () => {
      if (index < content.length) {
        const chunk = content.slice(index, index + chunkSize);
        index += chunkSize;

        res.write(`data: ${JSON.stringify({
          type: 'content',
          content: chunk,
          progress: Math.min(95, (index / content.length) * 100)
        })}\n\n`);

        // Send next chunk after a short delay
        setTimeout(sendChunk, 50);
      } else {
        // Send completion
        res.write(`data: ${JSON.stringify({
          type: 'complete',
          content: '',
          progress: 100,
          metadata: result.metadata
        })}\n\n`);

        clearTimeout(timeout);
        res.end();
      }
    };

    // Start sending chunks
    sendChunk();

  } catch (error) {
    console.error('❌ Streaming PRD generation error:', error);
    
    res.write(`data: ${JSON.stringify({
      type: 'error',
      error: error instanceof Error ? error.message : 'Failed to generate PRD'
    })}\n\n`);

    clearTimeout(timeout);
    res.end();
  }
}

export default router;
