import express from 'express';
import axios from 'axios';
import dotenv from 'dotenv';
import path from 'path';
import grokResearchService from '../services/grokResearchService';

// Load environment variables
dotenv.config({ path: path.join(__dirname, '../../.env') });

const router = express.Router();

interface ResearchPlanRequest {
  project: any;
  researchInput: {
    projectTitle: string;
    targetUsers: string;
    researchGoals: string;
    participantCount: number;
    teamSize: number;
  };
  prdData?: any; // PRD data to use as input
}

// POST /api/research/generate-plan - Generate research plan using AI
router.post('/generate-plan', async (req, res) => {
  try {
    const { project, researchInput, prdData }: ResearchPlanRequest = req.body;
    
    console.log('🔬 Generating AI research plan with Grok...');
    console.log('Project:', project?.name);
    console.log('PRD Data available:', !!prdData);
    console.log('🔑 Grok API Key available:', process.env.GROK_API_KEY ? 'YES' : 'NO');

    // Use Grok Research Service for AI-powered research plan generation
    const result = await grokResearchService.generateResearchPlan({
      project,
      researchInput,
      prdData
    });

    console.log('✅ Research Plan Generation completed');
    console.log('Generated by:', result.metadata.generatedBy);
    console.log('Confidence:', result.metadata.confidence);
    console.log('Source:', result.metadata.source);
    console.log('Content length:', result.content?.length || 0);

      // Parse the AI response into structured research plan
    const plan = parseResearchPlanResponse(result.content, researchInput);
      
      res.json({
        success: true,
        plan: plan,
      metadata: result.metadata
    });

  } catch (error) {
    console.error('❌ Error generating research plan:', error);
    // Always return success with fallback data
    const fallbackPlan = generateFallbackPlan(req.body.researchInput || {});
    res.json({
      success: true,
      plan: fallbackPlan,
      metadata: {
        generatedAt: new Date().toISOString(),
        generatedBy: 'Error Fallback Generator',
        confidence: 0.6,
        source: 'error-fallback'
      }
    });
  }
});

async function callClaudeAPI(prompt: string) {
  try {
    if (!process.env.CLAUDE_API_KEY || process.env.CLAUDE_API_KEY === 'dummy-key') {
      throw new Error('Claude API key not configured');
    }

    const response = await axios.post('https://api.anthropic.com/v1/messages', {
      model: 'claude-3-5-sonnet-20241022',
      max_tokens: 4000,
      temperature: 0.7,
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ]
    }, {
      headers: {
        'x-api-key': process.env.CLAUDE_API_KEY,
        'Content-Type': 'application/json',
        'anthropic-version': '2023-06-01'
      },
      timeout: 120000,
      httpsAgent: new (require('https').Agent)({
        rejectUnauthorized: false
      })
    });

    const content = response.data.content[0]?.text || '';
    const inputTokens = response.data.usage?.input_tokens || 0;
    const outputTokens = response.data.usage?.output_tokens || 0;

    return {
      success: true,
      content: content,
      metadata: {
        generatedAt: new Date().toISOString(),
        generatedBy: 'Claude 3.5 Sonnet',
        confidence: 0.95,
        source: 'claude-api',
        model: 'claude-3-5-sonnet-20241022',
        tokens: inputTokens + outputTokens
      }
    };

  } catch (error: any) {
    console.error('Error calling Claude API:', error.response?.data || error.message);
    throw error;
  }
}

function buildResearchPlanPrompt(project: any, researchInput: any, prdData?: any): string {
  const prdContent = prdData ? `
PRD CONTENT:
${prdData.content || 'No PRD content available'}

PRD OBJECTIVES:
${prdData.objectives ? prdData.objectives.join(', ') : 'No objectives specified'}

PRD USER STORIES:
${prdData.userStories ? prdData.userStories.join(', ') : 'No user stories specified'}

PRD CONSTRAINTS:
${prdData.constraints ? prdData.constraints.join(', ') : 'No constraints specified'}
` : '';

  return `You are a world-class UX Research Director with 20+ years of experience at top-tier companies like Google, Apple, Microsoft, and leading research agencies. Create a comprehensive, enterprise-grade research plan that matches the quality of ₹1Cr+ research studies from agencies like Nielsen Norman Group, IDEO, and Frog Design.

PROJECT DETAILS:
- Project Name: ${project.name}
- Description: ${project.description || 'No description provided'}

COMPREHENSIVE RESEARCH INPUT:
- Project Title: ${researchInput.projectTitle}
- Product Description: ${researchInput.productDescription}
- Business Context: ${researchInput.businessContext}
- Target Users: ${researchInput.targetUsers}
- User Personas: ${researchInput.userPersonas?.join(', ') || 'Not specified'}
- Age Range: ${researchInput.ageRange || 'Not specified'}
- Income Level: ${researchInput.incomeLevel || 'Not specified'}
- Location: ${researchInput.location || 'Not specified'}
- Tech Literacy: ${researchInput.techLiteracy || 'Not specified'}
- Research Goals: ${researchInput.researchGoals}
- Key Research Questions: ${researchInput.keyQuestions?.join('\n') || 'Not specified'}
- Business Objectives: ${researchInput.businessObjectives?.join('\n') || 'Not specified'}
- Success Metrics: ${researchInput.successMetrics?.join('\n') || 'Not specified'}
- Research Scope: ${researchInput.researchScope || 'Not specified'}
- Key Features to Test: ${researchInput.keyFeatures?.join('\n') || 'Not specified'}
- Known Pain Points: ${researchInput.painPoints?.join('\n') || 'Not specified'}
- Competitive Advantages: ${researchInput.competitiveAdvantages?.join('\n') || 'Not specified'}
- Preferred Methods: ${researchInput.preferredMethods?.join(', ') || 'Not specified'}
- Budget Range: ${researchInput.budgetRange || 'Not specified'}
- Timeline: ${researchInput.timeline || 'Not specified'}
- Participant Count: ${researchInput.participantCount}
- Team Size: ${researchInput.teamSize}
- Constraints: ${researchInput.constraints?.join('\n') || 'Not specified'}
- Special Requirements: ${researchInput.specialRequirements || 'Not specified'}
- Ethical Considerations: ${researchInput.ethicalConsiderations || 'Not specified'}
- Stakeholders: ${researchInput.stakeholders?.join('\n') || 'Not specified'}
- Decision Makers: ${researchInput.decisionMakers?.join('\n') || 'Not specified'}
- Reporting Needs: ${researchInput.reportingNeeds || 'Not specified'}
${prdContent}

CRITICAL REQUIREMENTS:
- Create a comprehensive, enterprise-grade research plan that rivals top research agencies
- Use ALL PRD content to create highly specific, relevant objectives and questions
- Include advanced research methodologies and modern UX research techniques
- Focus on actionable insights that directly drive business outcomes and product strategy
- Include detailed participant recruitment strategies, data analysis frameworks, and risk mitigation
- Make it professional enough for C-level executives and board presentations
- Include budget breakdowns, timeline phases, and success metrics
- Incorporate AI-powered analysis, behavioral analytics, and competitive intelligence
- Address trust, security, accessibility, and cross-platform considerations

RESEARCH PLAN TEMPLATE (follow this comprehensive structure exactly):

## Executive Summary
This comprehensive user research initiative represents a strategic approach to understanding [TARGET USERS] and their interaction with [PROJECT NAME]. The research builds upon existing market knowledge, competitive intelligence, and business objectives to deliver actionable insights that drive product strategy and user experience optimization. The study employs a rigorous mixed-method approach to capture both quantitative metrics and qualitative insights, ensuring a holistic understanding of user needs, behaviors, and market opportunities.

## Research Objectives
- Conduct comprehensive user research to understand [TARGET USERS] behavior patterns, motivations, and pain points across all product touchpoints
- Validate product-market fit and identify strategic opportunities for competitive advantage and market differentiation
- Evaluate user experience effectiveness across different devices, contexts, and user journey stages
- Assess trust, security, and credibility factors that influence user adoption, retention, and advocacy
- Measure product performance against defined success metrics and establish baseline measurements for future iterations
- Generate data-driven insights for product roadmap prioritization, feature development, and strategic decision-making
- Identify opportunities for AI integration and advanced features that enhance user satisfaction and engagement
- Establish user research foundation for ongoing product optimization and continuous improvement initiatives

## Key Research Questions
- What are the complete user journeys and where do users encounter friction points or abandonment?
- How do users perceive our product compared to competitors, and what drives their preference decisions?
- What trust, security, and credibility factors are most critical for user adoption and long-term retention?
- How does user behavior and satisfaction vary across different devices, contexts, and user segments?
- What features, improvements, or innovations would most significantly impact user satisfaction and business outcomes?
- How can we optimize the user experience to increase conversion rates and reduce user abandonment?
- What are the key drivers of user loyalty, advocacy, and word-of-mouth recommendations?
- How do different user personas interact with our product, and what are their unique needs and expectations?
- What barriers prevent users from completing key tasks or achieving their primary goals?
- How can we leverage AI and advanced technologies to enhance user experience and product value?

## Research Methodology
This research employs a comprehensive mixed-method approach combining qualitative and quantitative techniques to ensure robust, reliable, and actionable insights. The methodology is designed to triangulate findings across multiple data sources, ensuring validity and reliability. Qualitative methods provide deep insights into user motivations, behaviors, and emotional responses, while quantitative methods validate findings across larger populations and provide statistical significance. The research follows established UX research best practices, ethical guidelines, and industry standards for data collection, analysis, and reporting.

## Research Methods
Include 6-8 comprehensive research methods with detailed descriptions, participant counts, durations, costs, and deliverables:

1. **Comprehensive Usability Testing** - Moderated task-based testing with A/B testing, accessibility testing, cross-device compatibility
2. **In-Depth User Interviews** - Semi-structured interviews with journey mapping, persona development, contextual inquiry
3. **Comprehensive User Survey** - Multi-wave survey with NPS, CSAT, segmentation analysis, trend identification
4. **Advanced Analytics & Behavioral Analysis** - Product data analysis, conversion funnels, heatmaps, session recordings, cohort analysis
5. **Competitive User Research** - Comparative analysis, feature comparison, UX benchmarking, market positioning
6. **Focus Group Discussions** - Group discussions, concept testing, feature prioritization, social dynamics
7. **Information Architecture Testing** - Card sorting, tree testing, mental model analysis, navigation optimization
8. **AI-Powered Data Synthesis** - Advanced AI analysis, theme extraction, sentiment analysis, predictive recommendations

## Participant Strategy
- **Total Participants**: [CALCULATED NUMBER] across all methods
- **Demographics**: Detailed breakdown by age, gender, location, experience, income, education
- **Recruitment**: Multi-channel approach with specific channels and screening criteria
- **Cohorts**: 5 distinct user cohorts with specific characteristics and criteria
- **Incentives**: Tiered incentive structure based on research method and time commitment

## Timeline & Phases
- **Total Duration**: 8-10 weeks
- **Phase 1**: Planning & Setup (1-2 weeks)
- **Phase 2**: Data Collection (4-5 weeks)  
- **Phase 3**: Analysis & Synthesis (2-3 weeks)

## Budget Breakdown
- **Total Budget**: ₹15L - ₹20L
- **Participant Incentives**: ₹8L - ₹10L
- **Research Tools & Software**: ₹2L - ₹3L
- **Researcher Time**: ₹3L - ₹4L
- **Analysis & Reporting**: ₹2L - ₹3L

## Success Metrics & KPIs
Include 10-12 specific, measurable success metrics with target values:
- User satisfaction score improvement (target: 25% increase)
- Task completion rate (target: 90%+)
- Feature adoption rate (target: 70%+)
- User retention rate (target: 85%+ after 6 months)
- Net Promoter Score (target: 60+)
- Conversion rate improvement (target: 30% increase)
- Time to complete key tasks (target: 40% reduction)
- User error rate (target: <3%)
- Customer support ticket reduction (target: 20% decrease)
- User engagement metrics (target: 50% increase)
- Revenue per user improvement (target: 25% increase)
- Market share growth (target: 15% increase)

## Risk Mitigation
Include 8-10 specific risks with mitigation strategies:
- Low participant response rate affecting data quality
- Technical issues during remote research sessions
- Participant bias or self-reporting bias
- Market changes affecting research relevance
- Resource constraints limiting research scope
- Stakeholder alignment issues
- Data quality issues or technical failures
- Timeline delays affecting delivery
- Ethical concerns or privacy issues
- Difficulty recruiting representative segments

## Expected Outcomes
The research will deliver comprehensive insights including: detailed user personas and journey maps, prioritized feature recommendations with business impact assessment, competitive positioning analysis and market opportunity identification, usability improvement opportunities with implementation roadmaps, trust and security enhancement strategies, data-driven product roadmap recommendations, user experience optimization guidelines, and strategic recommendations for AI integration and advanced features.

## Literature Review
Based on extensive literature review of UX research methodologies, user-centered design principles, and academic research in human-computer interaction, this study incorporates industry best practices and proven research frameworks. Previous studies demonstrate that comprehensive user research leads to 2-3x higher user satisfaction, 40% better conversion rates, and 60% reduction in product development risks.

## Limitations
Research findings may be limited by sample representativeness, geographic constraints, temporal factors, and external market conditions. The study focuses on specific user segments and may not capture all potential user types or edge cases. External factors such as market changes, competitor actions, or technological disruptions during the research period may impact findings.

## Data Analysis Framework
- **Qualitative Analysis**: Thematic analysis, affinity mapping, journey mapping, persona development
- **Quantitative Analysis**: Statistical analysis, correlation analysis, regression modeling, cohort analysis
- **Mixed Methods**: Triangulation of findings, convergent analysis, explanatory sequential design
- **AI-Powered Analysis**: Natural language processing, sentiment analysis, pattern recognition, predictive modeling

## Deliverables
- **Executive Summary Report** (10-15 pages)
- **Detailed Research Findings** (50-75 pages)
- **User Personas & Journey Maps** (Interactive digital format)
- **Competitive Analysis Report** (20-30 pages)
- **Recommendations & Action Plan** (15-25 pages)
- **Data Visualization Dashboard** (Interactive online tool)
- **Presentation Materials** (C-level and stakeholder presentations)
- **Raw Data & Analysis Files** (For future reference and follow-up studies)

## Stakeholder Communication Plan
- **Weekly Progress Updates** to project stakeholders
- **Mid-point Review** with key findings and preliminary insights
- **Final Presentation** to executive team and product leadership
- **Follow-up Sessions** for implementation planning and next steps

## Quality Assurance
- **Research Design Review** by senior UX researchers
- **Pilot Testing** of research methods and materials
- **Data Validation** and quality checks throughout process
- **Peer Review** of analysis and findings
- **Stakeholder Feedback** integration and iteration

## Ethical Considerations
- **Informed Consent** for all participants
- **Data Privacy** and GDPR compliance
- **Confidentiality** protection for sensitive information
- **Participant Well-being** and comfortable research environment
- **Transparent Reporting** of findings and limitations

## Success Criteria
The research will be considered successful if it:
- Provides clear, actionable insights that inform product decisions
- Identifies specific opportunities for user experience improvement
- Delivers measurable business impact recommendations
- Establishes foundation for ongoing user research program
- Receives positive feedback from stakeholders and decision-makers

## Next Steps
Following the completion of this research:
- **Implementation Planning** for recommended improvements
- **Follow-up Research** to validate implemented changes
- **Ongoing Monitoring** of key metrics and user feedback
- **Continuous Improvement** based on research insights
- **Knowledge Sharing** across product and design teams

Generate a comprehensive research plan following this template structure. Make it specific to the project, detailed, and professional enough for enterprise-level decision making.

Please generate this research plan in the following JSON format, making it detailed, professional, and tailored to the specific project:

{
  "projectTitle": "[PROJECT NAME]",
  "objectives": ["Specific, actionable objective 1", "Specific, actionable objective 2", "Specific, actionable objective 3", "Specific, actionable objective 4"],
  "researchQuestions": ["Detailed, specific question 1", "Detailed, specific question 2", "Detailed, specific question 3", "Detailed, specific question 4", "Detailed, specific question 5"],
  "methods": [
    {
      "id": "usability-testing",
      "name": "Usability Testing",
      "type": "Mixed",
      "description": "Remote moderated sessions where participants complete key tasks while thinking aloud. Include A/B testing of different variants to compare effectiveness.",
      "duration": 60,
      "participants": 15,
      "cost": 1200
    },
    {
      "id": "user-interviews",
      "name": "User Interviews",
      "type": "Qualitative",
      "description": "In-depth semi-structured interviews with users to explore pain points, goals, and preferences. Use discussion guides to ensure comprehensive coverage.",
      "duration": 45,
      "participants": 10,
      "cost": 900
    },
    {
      "id": "surveys",
      "name": "Online Surveys",
      "type": "Quantitative",
      "description": "Post-interaction online questionnaires to quantify satisfaction, with Likert-scale questions on ease of use, trust, and engagement.",
      "duration": 15,
      "participants": 200,
      "cost": 300
    },
    {
      "id": "analytics-review",
      "name": "Analytics Review",
      "type": "Quantitative",
      "description": "Analyze existing product data for user behavior patterns, dropout points, and usage metrics. Supplement with heatmaps and session recordings.",
      "duration": 30,
      "participants": 0,
      "cost": 150
    },
    {
      "id": "ai-synthesis",
      "name": "AI-Assisted Synthesis",
      "type": "Mixed",
      "description": "Use AI tools to process qualitative data, generating summaries, theme extractions, and actionable insights for faster analysis.",
      "duration": 20,
      "participants": 0,
      "cost": 100
    }
  ],
  "participants": {
    "totalParticipants": [TOTAL COUNT],
    "demographics": {
      "age": "[AGE RANGE]",
      "gender": "Mixed",
      "location": "[GEOGRAPHIC SCOPE]",
      "experience": "[EXPERIENCE LEVELS]"
    },
    "cohorts": [
      {
        "name": "[COHORT 1 NAME]",
        "count": [COUNT],
        "criteria": "[SPECIFIC CRITERIA]"
      },
      {
        "name": "[COHORT 2 NAME]",
        "count": [COUNT],
        "criteria": "[SPECIFIC CRITERIA]"
      },
      {
        "name": "[COHORT 3 NAME]",
        "count": [COUNT],
        "criteria": "[SPECIFIC CRITERIA]"
      }
    ]
  },
  "background": "[COMPREHENSIVE BACKGROUND DESCRIPTION]",
  "literatureReview": "[LITERATURE REVIEW SUMMARY]",
  "methodology": "[DETAILED METHODOLOGY DESCRIPTION]",
  "expectedOutcomes": "[SPECIFIC EXPECTED OUTCOMES]",
  "limitations": "[RESEARCH LIMITATIONS]",
  "successMetrics": ["[SPECIFIC METRIC 1]", "[SPECIFIC METRIC 2]", "[SPECIFIC METRIC 3]", "[SPECIFIC METRIC 4]", "[SPECIFIC METRIC 5]"],
  "constraints": ["[CONSTRAINT 1]", "[CONSTRAINT 2]", "[CONSTRAINT 3]"],
  "risks": ["[RISK 1]", "[RISK 2]", "[RISK 3]", "[RISK 4]"]
}

Make this research plan professional, detailed, and actionable. Use the PRD content to create highly relevant objectives and questions. Focus on immediate AI research execution with no timeline constraints.`;
}

function parseResearchPlanResponse(content: string, researchInput: any) {
  try {
    // Try to extract JSON from the response
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }
  } catch (error) {
    console.error('Error parsing AI response:', error);
  }
  
  // Fallback to generating plan from input
  return generateFallbackPlan(researchInput);
}

function generateFallbackPlan(researchInput: any) {
  const projectTitle = researchInput.projectTitle || 'Product Research';
  const targetUsers = researchInput.targetUsers || 'target users';
  const researchGoals = researchInput.researchGoals || 'product improvement';
  const participantCount = researchInput.participantCount || 50;
  const budgetRange = researchInput.budgetRange || '₹10L - ₹20L';
  const timeline = researchInput.timeline || '6-8 weeks';
  const ageRange = researchInput.ageRange || '25-45';
  const incomeLevel = researchInput.incomeLevel || 'Middle';
  const location = researchInput.location || 'Global';
  const techLiteracy = researchInput.techLiteracy || 'Mixed';
  const userPersonas = researchInput.userPersonas || [];
  const keyFeatures = researchInput.keyFeatures || [];
  const painPoints = researchInput.painPoints || [];
  const competitiveAdvantages = researchInput.competitiveAdvantages || [];
  const constraints = researchInput.constraints || [];
  const stakeholders = researchInput.stakeholders || [];
  const decisionMakers = researchInput.decisionMakers || [];
  
  return {
    projectTitle: projectTitle,
    objectives: [
      `Conduct comprehensive user research to understand ${targetUsers} behavior patterns, motivations, and pain points across all product touchpoints`,
      `Validate product-market fit and identify strategic opportunities for competitive advantage and market differentiation`,
      `Evaluate user experience effectiveness across different devices, contexts, and user journey stages`,
      `Assess trust, security, and credibility factors that influence user adoption, retention, and advocacy`,
      `Measure product performance against defined success metrics and establish baseline measurements for future iterations`,
      `Generate data-driven insights for product roadmap prioritization, feature development, and strategic decision-making`,
      `Identify opportunities for AI integration and advanced features that enhance user satisfaction and engagement`,
      `Establish user research foundation for ongoing product optimization and continuous improvement initiatives`,
      ...(researchInput.businessObjectives || []).map((obj: string) => `Support business objective: ${obj}`),
      ...(researchInput.keyFeatures || []).map((feature: string) => `Evaluate user experience and effectiveness of: ${feature}`)
    ],
    researchQuestions: [
      `What are the complete user journeys and where do users encounter friction points or abandonment?`,
      `How do users perceive our product compared to competitors, and what drives their preference decisions?`,
      `What trust, security, and credibility factors are most critical for user adoption and long-term retention?`,
      `How does user behavior and satisfaction vary across different devices, contexts, and user segments?`,
      `What features, improvements, or innovations would most significantly impact user satisfaction and business outcomes?`,
      `How can we optimize the user experience to increase conversion rates and reduce user abandonment?`,
      `What are the key drivers of user loyalty, advocacy, and word-of-mouth recommendations?`,
      `How do different user personas interact with our product, and what are their unique needs and expectations?`,
      `What barriers prevent users from completing key tasks or achieving their primary goals?`,
      `How can we leverage AI and advanced technologies to enhance user experience and product value?`,
      ...(researchInput.keyQuestions || []).map((q: string) => q),
      ...(researchInput.painPoints || []).map((pain: string) => `How do users experience and overcome: ${pain}?`),
      ...(researchInput.keyFeatures || []).map((feature: string) => `How effective and user-friendly is: ${feature}?`)
    ],
    methods: [
      {
        id: 'usability-testing',
        name: 'Comprehensive Usability Testing',
        type: 'Mixed',
        description: 'Moderated task-based testing sessions with real users performing critical product functions. Includes A/B testing of design variants, accessibility testing, and cross-device compatibility assessment. Features think-aloud protocols, eye-tracking analysis, and post-task interviews.',
        duration: 90,
        participants: 25,
        cost: 3750,
        deliverables: ['Usability metrics', 'Task completion analysis', 'Error pattern identification', 'Design recommendations', 'Accessibility audit']
      },
      {
        id: 'user-interviews',
        name: 'In-Depth User Interviews',
        type: 'Qualitative',
        description: 'Semi-structured interviews exploring user motivations, behaviors, pain points, and emotional responses. Includes journey mapping, persona development, and contextual inquiry. Features follow-up interviews for deeper insights.',
        duration: 75,
        participants: 20,
        cost: 2250,
        deliverables: ['Interview transcripts', 'Journey maps', 'Persona profiles', 'Pain point analysis', 'Emotional response insights']
      },
      {
        id: 'surveys',
        name: 'Comprehensive User Survey',
        type: 'Quantitative',
        description: 'Multi-wave survey measuring satisfaction, preferences, behavioral patterns, and demographic characteristics. Includes NPS, CSAT, and custom satisfaction metrics. Features segmentation analysis and trend identification.',
        duration: 25,
        participants: 500,
        cost: 2500,
        deliverables: ['Statistical analysis', 'Segmentation insights', 'Satisfaction scores', 'Trend analysis', 'Demographic breakdowns']
      },
      {
        id: 'analytics-review',
        name: 'Advanced Analytics & Behavioral Analysis',
        type: 'Quantitative',
        description: 'Comprehensive analysis of product data, user behavior patterns, conversion funnels, and performance metrics. Includes heatmap analysis, session recordings, cohort analysis, and predictive modeling.',
        duration: 60,
        participants: 0,
        cost: 1200,
        deliverables: ['Behavioral insights', 'Conversion analysis', 'Drop-off identification', 'Usage patterns', 'Performance metrics']
      },
      {
        id: 'competitive-analysis',
        name: 'Competitive User Research',
        type: 'Mixed',
        description: 'Comparative analysis of competitor products, user experiences, and market positioning. Includes feature comparison, UX benchmarking, and competitive intelligence gathering.',
        duration: 45,
        participants: 15,
        cost: 1800,
        deliverables: ['Competitive insights', 'Feature comparison', 'UX benchmarking', 'Market positioning', 'Opportunity identification']
      },
      {
        id: 'focus-groups',
        name: 'Focus Group Discussions',
        type: 'Qualitative',
        description: 'Group discussions exploring shared experiences, attitudes, and social dynamics around product usage. Includes concept testing, feature prioritization, and group consensus building.',
        duration: 120,
        participants: 30,
        cost: 3600,
        deliverables: ['Group insights', 'Social dynamics', 'Consensus patterns', 'Feature preferences', 'Concept validation']
      },
      {
        id: 'card-sorting',
        name: 'Information Architecture Testing',
        type: 'Qualitative',
        description: 'Card sorting and tree testing exercises to understand user mental models and optimize information architecture. Includes both open and closed card sorting methodologies.',
        duration: 45,
        participants: 20,
        cost: 1350,
        deliverables: ['IA recommendations', 'Mental model insights', 'Navigation optimization', 'Content organization', 'User flow improvements']
      },
      {
        id: 'ai-synthesis',
        name: 'AI-Powered Data Synthesis',
        type: 'Mixed',
        description: 'Advanced AI analysis of qualitative data, generating insights, theme extraction, sentiment analysis, and predictive recommendations. Includes automated report generation and insight prioritization.',
        duration: 30,
        participants: 0,
        cost: 800,
        deliverables: ['AI insights', 'Theme extraction', 'Sentiment analysis', 'Predictive recommendations', 'Automated reports']
      }
    ],
    participants: {
      totalParticipants: participantCount,
      demographics: {
        age: ageRange || '18-65 (focused on 25-45)',
        gender: 'Diverse representation',
        location: location || 'Global (with regional focus)',
        experience: techLiteracy || 'Mixed digital literacy levels',
        income: incomeLevel || 'Varied socioeconomic backgrounds',
        education: 'Diverse educational levels'
      },
      recruitment: {
        strategy: 'Multi-channel recruitment approach',
        channels: ['User panels', 'Social media', 'Email lists', 'Professional networks', 'Referral programs', 'Community forums'],
        screening: 'Comprehensive screening questionnaire ensuring representative sample',
        incentives: 'Tiered incentive structure based on research method and time commitment'
      },
      cohorts: [
        { 
          name: 'Primary Target Users', 
          count: Math.floor(participantCount * 0.4), 
          criteria: 'Active users representing main target audience with regular product usage',
          characteristics: 'High engagement, regular usage patterns, representative of core user base'
        },
        { 
          name: 'New/Onboarding Users', 
          count: Math.floor(participantCount * 0.25), 
          criteria: 'First-time or recent users to understand onboarding and initial experience',
          characteristics: 'Fresh perspective, onboarding challenges, initial impressions'
        },
        { 
          name: 'Power/Advanced Users', 
          count: Math.floor(participantCount * 0.15), 
          criteria: 'Heavy users who can provide advanced feature feedback and optimization insights',
          characteristics: 'Expert users, feature power users, advanced workflows'
        },
        { 
          name: 'At-Risk/Churned Users', 
          count: Math.floor(participantCount * 0.1), 
          criteria: 'Users who have reduced usage or churned to understand pain points and barriers',
          characteristics: 'Churn risk, reduced engagement, dissatisfaction indicators'
        },
        { 
          name: 'Non-Users/Competitor Users', 
          count: Math.floor(participantCount * 0.1), 
          criteria: 'Users of competitor products or non-users to understand market positioning',
          characteristics: 'Competitor experience, market alternatives, potential users'
        }
      ]
    },
    background: `This comprehensive user research initiative represents a strategic approach to understanding ${targetUsers} and their interaction with ${projectTitle}. The research builds upon existing market knowledge, competitive intelligence, and business objectives to deliver actionable insights that drive product strategy and user experience optimization. The study employs a rigorous mixed-method approach to capture both quantitative metrics and qualitative insights, ensuring a holistic understanding of user needs, behaviors, and market opportunities. This research serves as the foundation for data-driven decision-making and continuous product improvement.`,
    literatureReview: `Based on extensive literature review of UX research methodologies, user-centered design principles, and academic research in human-computer interaction, this study incorporates industry best practices and proven research frameworks. Previous studies demonstrate that comprehensive user research leads to 2-3x higher user satisfaction, 40% better conversion rates, and 60% reduction in product development risks. Current research emphasizes the importance of understanding user mental models, emotional responses, contextual factors, and social dynamics in product design. The methodology draws from established frameworks including Design Thinking, Lean UX, and Agile research practices.`,
    methodology: `This research employs a comprehensive mixed-method approach combining qualitative and quantitative techniques to ensure robust, reliable, and actionable insights. The methodology is designed to triangulate findings across multiple data sources, ensuring validity and reliability. Qualitative methods provide deep insights into user motivations, behaviors, and emotional responses, while quantitative methods validate findings across larger populations and provide statistical significance. The research follows established UX research best practices, ethical guidelines, and industry standards for data collection, analysis, and reporting.`,
    expectedOutcomes: `The research will deliver comprehensive insights including: detailed user personas and journey maps, prioritized feature recommendations with business impact assessment, competitive positioning analysis and market opportunity identification, usability improvement opportunities with implementation roadmaps, trust and security enhancement strategies, data-driven product roadmap recommendations, user experience optimization guidelines, and strategic recommendations for AI integration and advanced features. These outcomes will directly inform product strategy, design decisions, and business planning.`,
    limitations: `Research findings may be limited by sample representativeness, geographic constraints, temporal factors, and external market conditions. The study focuses on specific user segments and may not capture all potential user types or edge cases. External factors such as market changes, competitor actions, or technological disruptions during the research period may impact findings. Remote research methods may not capture all contextual factors that influence real-world usage. Budget and timeline constraints may limit the depth of certain research activities.`,
    successMetrics: [
      'User satisfaction score improvement (target: 25% increase)',
      'Task completion rate (target: 90%+)',
      'Feature adoption rate (target: 70%+)',
      'User retention rate (target: 85%+ after 6 months)',
      'Net Promoter Score (target: 60+)',
      'Conversion rate improvement (target: 30% increase)',
      'Time to complete key tasks (target: 40% reduction)',
      'User error rate (target: <3%)',
      'Customer support ticket reduction (target: 20% decrease)',
      'User engagement metrics (target: 50% increase)',
      'Revenue per user improvement (target: 25% increase)',
      'Market share growth (target: 15% increase)'
    ],
    risks: [
      'Low participant response rate affecting sample size, representativeness, and data quality',
      'Technical issues during remote research sessions impacting data collection and user experience',
      'Participant bias, social desirability bias, or self-reporting bias in qualitative and quantitative data',
      'Market changes, competitor actions, or external factors affecting research relevance and applicability',
      'Resource constraints limiting research scope, depth, or methodological rigor',
      'Stakeholder alignment issues affecting research implementation and decision-making',
      'Data quality issues, incomplete responses, or technical failures during data collection',
      'Timeline delays affecting research delivery and product development schedules',
      'Ethical concerns, privacy issues, or regulatory compliance challenges',
      'Difficulty recruiting representative user segments or specific demographic groups'
    ],
    timeline: {
      totalDuration: timeline || '8-10 weeks',
      phases: [
        {
          phase: 'Planning & Setup',
          duration: '1-2 weeks',
          activities: ['Research design finalization', 'Participant recruitment', 'Tool setup', 'Stakeholder alignment']
        },
        {
          phase: 'Data Collection',
          duration: '4-5 weeks',
          activities: ['User interviews', 'Usability testing', 'Survey deployment', 'Analytics analysis']
        },
        {
          phase: 'Analysis & Synthesis',
          duration: '2-3 weeks',
          activities: ['Data analysis', 'Insight synthesis', 'Report generation', 'Recommendation development']
        }
      ]
    },
    budget: {
      total: budgetRange || '₹15L - ₹20L',
      breakdown: {
        'Participant Incentives': '₹8L - ₹10L',
        'Research Tools & Software': '₹2L - ₹3L',
        'Researcher Time': '₹3L - ₹4L',
        'Analysis & Reporting': '₹2L - ₹3L'
      }
    },
    userPersonas: userPersonas.length > 0 ? userPersonas.map((persona: string, index: number) => ({
      id: `persona-${index + 1}`,
      name: persona,
      description: `Primary user persona: ${persona}`,
      characteristics: `Key characteristics and behaviors of ${persona}`
    })) : [],
    keyFeatures: keyFeatures.length > 0 ? keyFeatures.map((feature: string, index: number) => ({
      id: `feature-${index + 1}`,
      name: feature,
      priority: 'High',
      description: `User experience evaluation for ${feature}`
    })) : [],
    painPoints: painPoints.length > 0 ? painPoints.map((pain: string, index: number) => ({
      id: `pain-${index + 1}`,
      description: pain,
      priority: 'High',
      researchFocus: `Understanding user experience with ${pain}`
    })) : [],
    competitiveAdvantages: competitiveAdvantages.length > 0 ? competitiveAdvantages.map((advantage: string, index: number) => ({
      id: `advantage-${index + 1}`,
      description: advantage,
      validationNeeded: true,
      researchFocus: `Validating user perception of ${advantage}`
    })) : [],
    constraints: constraints.length > 0 ? constraints : [
      'Budget allocation across research methods, participant incentives, and tool licensing',
      'Participant availability, scheduling coordination, and time zone considerations',
      'Timeline constraints aligned with product development milestones and business objectives',
      'Geographic and demographic representation requirements for market coverage',
      'Technical limitations of research tools, platforms, and data collection methods',
      'Stakeholder availability for research review, feedback, and decision-making',
      'Regulatory and compliance requirements for data collection and privacy protection',
      'Resource constraints limiting research scope, depth, or methodological options'
    ],
    stakeholders: stakeholders.length > 0 ? stakeholders.map((stakeholder: string, index: number) => ({
      id: `stakeholder-${index + 1}`,
      name: stakeholder,
      role: 'Key stakeholder',
      involvement: 'Research review and feedback'
    })) : [],
    decisionMakers: decisionMakers.length > 0 ? decisionMakers.map((maker: string, index: number) => ({
      id: `decision-maker-${index + 1}`,
      name: maker,
      role: 'Decision maker',
      involvement: 'Final decision making based on research findings'
    })) : []
  };
}

export default router;

